# vim: ts=2 sw=2 et
version: '3'

services:
  webchaind:
    build: ./webchaind
    volumes:
      - ~/.webchain:/home/webchaind/.webchain
    expose:
       - "8545"
       - "8546"

  webchain-cli:
    depends_on:
      - webchaind
    build: ./webchain-cli
    network_mode: "service:webchaind"
    volumes:
      - ~/.webchain:/home/webchain/.webchain
      - ~/.webchain-vault:/home/webchain/.webchain-vault
